### PR TITLE
feat: sync to async codemod

### LINKED ISSUE #1: Add WDIO sync -> async codemod
It would be nice to have a `codemod` that can convert `wdio` sync code to async.

### PR DESCRIPTION
**Pull request by alk-mandrianarijaona**
fixes #1 

from: 

```
describe('my test', () => {
    it('should fetch menu links and visit each page', () => {
    	const links =  $$('#menu a')
	    links.forEach((link) => {
    	    link.click()
    	})
    })
  
  it('should demonstrate the click command', () => {
      const myButton =  $('#myButton')
      myButton.click()
      const myText = $('#someText')
      const text = myText.getText()
      assert(text === 'I was clicked') // true

      $('body').click()
    })
})
```

to: 
```
describe('my test', () => {
    it('should fetch menu links and visit each page', async () => {
        const links =  await $$('#menu a')
            links.forEach((link) => {
            link.click()
        })
   })

  it('should demonstrate the click command', async () => {
      const myButton =  await $('#myButton')
      myButton.click()
      const myText = await $('#someText')
      const text = myText.getText()
      assert(text === 'I was clicked') // true

      await (await $('body')).click()
    })
})
```

### CODE REVIEW

**Comment by christian-bromann** [comment]
@alk-mandrianarijaona very appreciate you are tackling this. Let me know if I can be of any help.

**Comment by alk-mandrianarijaona** [comment]
> @alk-mandrianarijaona very appreciate you are tackling this. Let me know if I can be of any help.

Thank you @christian-bromann, I will let you know if I need anything

**Comment by lacell75** [comment]
any news on this topic? I will appreciate having this codemode

**Comment by alk-mandrianarijaona** [comment]
hi @lacell75 I will try to work back on it in the next days

**Comment by lacell75** [comment]
Thanks!

**Comment by mo** [comment]
I tried out this codemod and wrote some feedback here:
https://github.com/webdriverio/codemod/issues/1#issuecomment-962576283

Thanks for working on this btw! :+1:

**Comment by alk-mandrianarijaona** [comment]
This is replaced by a more advanced PR https://github.com/webdriverio/codemod/pull/53

**Pull request closed without merging**
