### PR TITLE
Document async codemod dependency on v7.9+

### PR DESCRIPTION
**Pull request by prust**
@christian-bromann: This pull request documents the async codemod's dependency on WebDriver 7.9+, as discussed in https://github.com/webdriverio/codemod/issues/89#issuecomment-1445448642.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@prust thanks for the PR, mind signing the CLA?

**Comment by prust** [comment]
@christian-bromann: not at all, but FYI the linux foundation's EasyCLA tool seems to be struggling at the moment (I got a 500 error adding my manager on the "Identify CLA Manager" screen, my manager then tried the "Are you a CLA Manager for your organization?" workflow, but that appears to be having issues as well. He'll try again tomorrow.

https://status.linuxfoundation.org does say "Service Under Maintenance", so perhaps that's the issue? (I don't see a status line that's specific to EasyCLA):

image

**Comment by prust** [comment]
@christian-bromann: FYI, the CLA is now signed

**Review by christian-bromann — APPROVED** [review]
👍 Thank you!

**Pull request merged**
